### ISSUE TITLE
Error in Form Submission

### ISSUE THREAD

**Issue by LailaSamared** [louissosthenes9/COFAS-2025#8]
Inasema hivyo eti when i try to submit form details
![Screenshot (7)](https://github.com/user-attachments/assets/529425b1-0d25-4da6-ab89-ce99439c8991)
_

**Comment by louissosthenes9** [comment]
- Aaaah ok...ingia kwenye application/migrations....delete every file except __init__.py.............then 
- andika python manage.py makemigrations 
- python manage.py migrate

**Comment by louissosthenes9** [comment]
Give me feedback for anything
